-- ====================================================================
-- NMAO — motivational sayings seed (shown at reveal to non-placers).
-- Source: Bradley's collection (OCR-cleaned). Run once after the schema.
-- Idempotent: unique(text) + on conflict do nothing.
-- ====================================================================
insert into motivational_sayings (seq, text, author) values
  (1, 'Train with passion, fight with heart, and never give up.', null),
  (2, 'Every setback is an opportunity for a comeback.', null),
  (3, 'Success is not final, failure is not fatal. It''s the courage to continue that counts.', null),
  (4, 'The only limit is the one you set for yourself.', null),
  (5, 'Believe in yourself and your abilities, and you can achieve anything.', null),
  (6, 'A black belt is a white belt who never gave up.', null),
  (7, 'The harder you work, the luckier you get.', null),
  (8, 'Strength comes not from physical capacity but from an indomitable will.', null),
  (9, 'Success is the sum of small efforts repeated day in and day out.', null),
  (10, 'Don''t wait for the perfect moment, take the moment and make it perfect.', null),
  (11, 'Obstacles are what you see when you take your eyes off the goal.', null),
  (12, 'In the middle of difficulty lies opportunity.', null),
  (13, 'A champion is someone who gets up when they can''t.', null),
  (14, 'The journey is the reward.', null),
  (15, 'The greatest glory is not in never falling, but in rising every time we fall.', null),
  (16, 'The only way to do great work is to love what you do.', null),
  (17, 'Success is not about winning every battle, but learning from every defeat.', null),
  (18, 'The harder you train, the luckier you become.', null),
  (19, 'Your attitude determines your altitude.', null),
  (20, 'Don''t count the days, make the days count.', null),
  (21, 'A winner is a dreamer who never gives up.', null),
  (22, 'Do today what others won''t, so tomorrow you can do what others can''t.', null),
  (23, 'The only bad workout is the one you didn''t do.', null),
  (24, 'Your only limit is you.', null),
  (25, 'Sweat now, shine later.', null),
  (26, 'The pain you feel today will be the strength you feel tomorrow.', null),
  (27, 'Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer'),
  (28, 'Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson'),
  (29, 'Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
  (30, 'Champions aren''t made in the gyms. Champions are made from something they have deep inside them—a desire, a dream, a vision.', 'Muhammad Ali'),
  (31, 'The only way to predict the future is to create it.', 'Peter Drucker'),
  (32, '1 don''t count my sit-ups; | only start counting when it starts hurting because they’re the only ones that count.', 'Muhammad Ali'),
  (33, 'The best way to predict your future is to create it.', 'Abraham Lincoln'),
  (34, 'The more you sweat in training, the less you bleed in battle.', 'Richard Marcinko'),
  (35, 'The difference between the impossible and the possible lies in a person''s determination.', 'Tommy Lasorda'),
  (36, 'I''ve failed over and over and over again in my life. And that is why | succeed.', 'Michael Jordan'),
  (37, 'Strength does not come from physical capacity. It comes from an indomitable will.', 'Mahatma Gandhi'),
  (38, 'A journey of a thousand miles begins with a single step.', 'Lao Tzu'),
  (39, 'The secret of getting ahead is getting started.', 'Mark Twain'),
  (40, 'You have to expect things of yourself before you can do them.', 'Michael Jordan'),
  (41, 'Success is not just about making money. It''s about making a difference.', null),
  (42, 'It always seems impossible until it''s done.', 'Nelson Mandela'),
  (43, 'lam not a product of my circumstances. | am a product of my decisions.', 'Stephen Covey'),
  (44, 'Don''t let what you cannot do interfere with what you can do.', 'John Wooden'),
  (45, 'The only place where success comes before work is in the dictionary.', 'Vidal Sassoon'),
  (46, 'Success is not the absence of failure; it''s the persistence through failure.', 'Aisha Tyler'),
  (47, 'You don''t have to be great to start, but you have to start to be great.', 'Zig Ziglar'),
  (48, 'The more you know yourself, the more you can grow.', 'John C. Maxwell'),
  (49, 'Success is not in what you have, but who you are.', 'Bo Bennett'),
  (50, 'Success is not the destination, it''s the journey.', 'Zig Ziglar - Certainly! Here are motivational sayings with quotes and credit for numbers 51-150:'),
  (51, 'The harder you work for something, the greater you''ll feel when you achieve it.', null),
  (52, 'Success is stumbling from failure to failure with no loss of enthusiasm.', 'Winston Churchill'),
  (53, 'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.', 'Christian D. Larson'),
  (54, 'You miss 100% of the shots you don''t take.', 'Wayne Gretzky'),
  (55, 'The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt'),
  (56, 'The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt'),
  (57, 'The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson'),
  (58, 'Success is not about being the best. It''s about being better than you were yesterday.', null),
  (59, 'Your time is limited, don''t waste it living someone else''s life.', 'Steve Jobs'),
  (60, 'Do what you can, with what you have, where you are.', 'Theodore Roosevelt'),
  (61, 'The best revenge is massive success.', 'Frank Sinatra'),
  (62, 'Great things never come from comfort zones.', null),
  (63, 'The expert in anything was once a beginner.', 'Helen Hayes'),
  (64, 'Your dream doesn''t have an expiration date. Take a deep breath and try again.', 'KT Witten'),
  (65, 'The only limit is your mind.', null),
  (66, 'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down.', 'Chantal Sutherland'),
  (67, 'Life is 10% what happens to us and 90% how we react to it.', 'Charles R. Swindoll'),
  (68, 'Dream big and dare to fail.', 'Norman Vaughan'),
  (69, 'Your desire to change must be greater than your desire to stay the same.', null),
  (70, 'Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller'),
  (71, 'The secret to getting ahead is getting started.', 'Mark Twain'),
  (72, 'It''s not about how hard you hit. It''s about how hard you can get hit and keep moving forward.', 'Rocky Balboa'),
  (73, 'Obstacles are those frightful things you see when you take your eyes off the goal.', 'Henry Ford'),
  (74, 'Success is not final, failure is not fatal: It is the courage to continue that counts.', 'Winston Churchill'),
  (75, 'The biggest risk is not taking any risk.', 'Mark Zuckerberg'),
  (76, 'Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill'),
  (77, 'You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis'),
  (78, 'You are the creator of your own destiny.', 'Swami Vivekananda'),
  (79, 'The more you dream, the more you achieve.', 'Michael Phelps'),
  (80, 'If you can dream it, you can - achieve it.', 'Zig Ziglar'),
  (81, 'The only thing standing between you and your goal is the story you keep telling yourself as to why you can''t achieve it.', 'Jordan Belfort'),
  (82, 'I don''t count my sit-ups; | only start counting when it starts hurting because they’re the only ones that count.', 'Muhammad Ali'),
  (83, 'Strength doesn''t come from winning. Your struggles develop your strengths.', 'Arnold Schwarzenegger'),
  (84, 'If you want to achieve greatness, stop asking for permission.', null),
  (85, 'The only person you should try to be better than is the person you were yesterday.', null),
  (86, 'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.', 'Chantal Sutherland'),
  (87, 'You have to fight through some bad days to earn the best days of your life.', null),
  (88, 'Never give up, for that is just the place and time that the tide will turn.', 'Harriet Beecher Stowe'),
  (89, 'The best way to predict the future is to create it.', 'Peter Drucker'),
  (90, 'The best view comes after the hardest climb.', null),
  (91, 'A year from now, you will wish you had started today.', 'Karen Lamb'),
  (92, 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'Albert Schweitzer'),
  (93, 'Doubt kills more dreams than failure ever will.', 'Suzy Kassem'),
  (94, 'Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau'),
  (95, 'Don''t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'Roy T. Bennett'),
  (96, 'Do not wait for opportunity. Create it.', 'George Bernard Shaw'),
  (97, 'Don''t limit your challenges. Challenge your limits.', null),
  (98, 'If it doesn''t challenge you, it won''t change you.', 'Fred DeVito'),
  (99, 'A year from now, you''ll wish you had started today.', 'Karen Lamb'),
  (100, 'Every accomplishment starts with the decision to try.', null),
  (101, 'Strive for progress, not perfection.', null),
  (102, 'Success is not just about reaching your goals; it''s about who you become in the process.', null),
  (103, 'Don''t wait for opportunity. Create it.', null),
  (104, 'Every great journey begins with a single step.', null),
  (105, 'Your dreams are worth fighting for.', null),
  (106, 'The biggest risk is not taking any risk. In a world that''s changing quickly, the only strategy that is guaranteed to fail is not taking risks.', 'Mark Zuckerberg'),
  (107, 'Challenges are what make life interesting. Overcoming them is what makes life meaningful.', 'Joshua J. Marine'),
  (108, 'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.', 'Chantal Sutherland'),
  (109, 'Your life does not get better by chance, it gets - better by change.', 'Jim Rohn'),
  (110, 'The difference between a stumbling block and a stepping stone is how high you raise your foot.', 'Benny Lewis'),
  (111, 'Be fearless in the pursuit of what sets your soul on fire.', 'Jennifer Lee')
on conflict (text) do nothing;

select count(*) as sayings_loaded from motivational_sayings;
