// =====================================================================
// EDGE FUNCTION: register-school
// Self-serve, minimal-upfront OFFICIAL signup for the join.nmao.us form.
// Turns the old "leave a lead" form into a real signup: creates the school
// (join code auto-generated by trigger), stamps the owner contact, then calls
// send-school-setup-link — which ensures the owner's login account and emails
// them a password-setup link to school.nmao.us. From there the owner sets a
// password and completes Stripe Connect to receive entry-fee payouts.
//
// The school is inert until the owner clicks the emailed link (proves email
// ownership) and finishes Connect, so a junk submit just leaves a dormant row.
//
// DEPLOY: name = register-school, **Verify JWT OFF** (public form).
//   supabase functions deploy register-school --no-verify-jwt --project-ref oxzuavpyoetchwebdejp
// Env: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (auto), RESEND_API_KEY (optional),
//      EMAIL_FROM (optional), LEADS_NOTIFY_EMAIL (optional; default support@nmao.us).
// =====================================================================
// deno-lint-ignore-file no-explicit-any
import { createClient } from "jsr:@supabase/supabase-js@2";

const URL_ = Deno.env.get("SUPABASE_URL")!;
const SERVICE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const RESEND = Deno.env.get("RESEND_API_KEY");
const FROM = Deno.env.get("EMAIL_FROM") || "NMAO Tournament <noreply@nmao.us>";
const NOTIFY = Deno.env.get("LEADS_NOTIFY_EMAIL") || "support@nmao.us";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (o: unknown, s = 200) => new Response(JSON.stringify(o), { status: s, headers: { ...cors, "Content-Type": "application/json" } });
const clean = (v: unknown, n = 200) => String(v ?? "").trim().slice(0, n);
const isEmail = (s: string) => /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(s);

async function sendSetupLink(schoolId: string) {
  try {
    await fetch(`${URL_}/functions/v1/send-school-setup-link`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${SERVICE}` },
      body: JSON.stringify({ school_id: schoolId }),
    });
  } catch (e) { console.error("setup-link (non-fatal):", (e as Error).message); }
}

async function notify(name: string, email: string, phone: string, isNew: boolean) {
  if (!RESEND) return;
  try {
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: FROM, to: [NOTIFY],
        subject: `${isNew ? "New school signed up" : "School re-requested setup"}: ${name}`,
        html: `<p><strong>${name}</strong> ${isNew ? "signed up" : "re-requested a setup link"} via join.nmao.us.</p>
               <p>Email: ${email}<br>Phone: ${phone || "—"}</p>`,
      }),
    });
  } catch (_e) { /* non-fatal */ }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (req.method !== "POST") return json({ ok: false, error: "POST only" }, 405);

  try {
    const body = await req.json().catch(() => ({}));
    const name = clean(body.school_name ?? body.name, 160);
    const email = clean(body.email, 200).toLowerCase();
    const phone = clean(body.phone, 40);
    if (!name) return json({ ok: false, error: "Please enter your school name." }, 200);
    if (!isEmail(email)) return json({ ok: false, error: "Please enter a valid email address." }, 200);

    const svc = createClient(URL_, SERVICE, { auth: { persistSession: false } });

    // Dedupe by contact email — never create a second school for the same owner.
    const { data: existing } = await svc.from("schools")
      .select("id, name, join_code").eq("contact_email_norm", email).maybeSingle();

    if (existing) {
      await sendSetupLink((existing as any).id);
      await notify(name, email, phone, false);
      return json({ ok: true, already: true, join_code: (existing as any).join_code ?? null,
        message: "You're already registered — we've re-sent your setup link. Check your email." });
    }

    // Create the school (status defaults to 'active'; join_code auto by trigger;
    // contact_email_norm is a generated column — do NOT set it).
    const { data: created, error: cErr } = await svc.from("schools")
      .insert({ name, contact_email: email, phone: phone || null })
      .select("id, join_code").single();
    if (cErr || !created) return json({ ok: false, error: "Could not create your school. Please try again." }, 200);

    await sendSetupLink((created as any).id);
    await notify(name, email, phone, true);

    return json({ ok: true, school_id: (created as any).id, join_code: (created as any).join_code ?? null,
      message: "You're in! Check your email for a link to set your password and finish setup." });
  } catch (e) {
    return json({ ok: false, error: (e as any)?.message || "server_error" }, 500);
  }
});
