-- ============================================================
-- Dueling — notifications (in-app core)
-- notifications table (per competitor; guardian reads via competitor_ids()) +
-- notification_prefs (guardian-controllable, default on). Generated by TRIGGERS
-- on duels/monthly_reveals (no RPC rewrites) + a reminder cron.
-- Push delivery (Expo) is a later layer: register push tokens + an EF that reads
-- new notifications and sends. This core is what the app reads/subscribes to.
-- Spec: DUELING-DECISIONS.md §13.
-- ============================================================

create table if not exists notifications (
  id            uuid primary key default gen_random_uuid(),
  competitor_id uuid not null references competitors(id) on delete cascade,
  type          text not null,
  title         text not null,
  body          text,
  data          jsonb,
  read          boolean not null default false,
  created_at    timestamptz not null default now()
);
create index if not exists notifications_recipient_idx on notifications(competitor_id, created_at desc);
create index if not exists notifications_unread_idx on notifications(competitor_id) where read = false;

create table if not exists notification_prefs (
  competitor_id uuid not null references competitors(id) on delete cascade,
  type          text not null,
  enabled       boolean not null default true,
  primary key (competitor_id, type)
);

alter table notifications      enable row level security;
alter table notification_prefs enable row level security;
grant select on notifications to authenticated;
grant select, insert, update, delete on notification_prefs to authenticated;

drop policy if exists notifications_read on notifications;
create policy notifications_read on notifications for select to authenticated
  using (nmao.is_staff() or competitor_id in (select nmao.competitor_ids()));
drop policy if exists np_rw on notification_prefs;
create policy np_rw on notification_prefs for all to authenticated
  using (nmao.is_staff() or competitor_id in (select nmao.competitor_ids()))
  with check (competitor_id in (select nmao.competitor_ids()));

-- insert a notification unless the recipient turned that type off
create or replace function nmao.notify(p_competitor uuid, p_type text, p_title text, p_body text, p_data jsonb default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_competitor is null then return; end if;
  if exists (select 1 from notification_prefs where competitor_id = p_competitor and type = p_type and enabled = false) then return; end if;
  insert into notifications (competitor_id, type, title, body, data) values (p_competitor, p_type, p_title, p_body, p_data);
end;
$$;

-- mark read (own only)
create or replace function public.mark_notification_read(p_id uuid)
returns void language sql security definer set search_path = public as $$
  update notifications set read = true
  where id = p_id and competitor_id in (select nmao.competitor_ids());
$$;
create or replace function public.mark_all_notifications_read()
returns void language sql security definer set search_path = public as $$
  update notifications set read = true
  where competitor_id in (select nmao.competitor_ids()) and read = false;
$$;
grant execute on function public.mark_notification_read(uuid) to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;

-- ---- duel lifecycle → notifications ----
create or replace function nmao.tg_duel_notify()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if TG_OP = 'INSERT' then
    if NEW.status = 'pending' then
      perform nmao.notify(NEW.opponent_id, 'challenge_received', 'New duel challenge ⚔️',
        'You have been challenged — accept within 48 hours.', jsonb_build_object('duel_id', NEW.id, 'type', NEW.type));
    end if;
    return NEW;
  end if;

  if NEW.status is distinct from OLD.status then
    if NEW.status = 'accepted' then
      perform nmao.notify(NEW.challenger_id, 'challenge_accepted', 'Challenge accepted!',
        'It is on — both of you have 72 hours to upload.', jsonb_build_object('duel_id', NEW.id));
    elsif NEW.status = 'declined' then
      perform nmao.notify(NEW.challenger_id, 'challenge_declined', 'Challenge declined',
        'That challenge was declined — find another opponent!', jsonb_build_object('duel_id', NEW.id));
    elsif NEW.status = 'voting' then
      perform nmao.notify(NEW.challenger_id, 'duel_live', 'Your duel is live!', 'Both entries are in — the community is voting.', jsonb_build_object('duel_id', NEW.id));
      perform nmao.notify(NEW.opponent_id,   'duel_live', 'Your duel is live!', 'Both entries are in — the community is voting.', jsonb_build_object('duel_id', NEW.id));
    elsif NEW.status in ('complete','no_contest') then
      perform nmao.notify(NEW.challenger_id, 'duel_result', 'Duel result is in', 'Tap to see how your duel went.', jsonb_build_object('duel_id', NEW.id, 'result', NEW.result));
      perform nmao.notify(NEW.opponent_id,   'duel_result', 'Duel result is in', 'Tap to see how your duel went.', jsonb_build_object('duel_id', NEW.id, 'result', NEW.result));
    end if;
  end if;

  if NEW.overtime_until is not null and OLD.overtime_until is null then
    perform nmao.notify(NEW.challenger_id, 'sudden_death', 'Sudden death! ⚔️', 'Your duel is tied — 60 minutes of overtime voting!', jsonb_build_object('duel_id', NEW.id));
    perform nmao.notify(NEW.opponent_id,   'sudden_death', 'Sudden death! ⚔️', 'Your duel is tied — 60 minutes of overtime voting!', jsonb_build_object('duel_id', NEW.id));
  end if;
  return NEW;
end;
$$;
drop trigger if exists duels_notify on duels;
create trigger duels_notify after insert or update on duels for each row execute function nmao.tg_duel_notify();

-- ---- monthly reveal → notification ----
create or replace function nmao.tg_reveal_notify()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform nmao.notify(NEW.competitor_id, 'reveal_ready', 'Your monthly reveal is ready ✨',
    'See the badges and highlights you earned this month.', jsonb_build_object('period', NEW.period));
  return NEW;
end;
$$;
drop trigger if exists monthly_reveals_notify on monthly_reveals;
create trigger monthly_reveals_notify after insert on monthly_reveals for each row execute function nmao.tg_reveal_notify();

-- ---- reminder cron: upload reminder + voting-closes-soon (deduped per duel+type) ----
create or replace function nmao.duel_reminders()
returns int language plpgsql security definer set search_path = public as $$
declare n int := 0; r record;
begin
  for r in select * from duels where status = 'accepted' and upload_deadline between now() and now() + interval '12 hours' loop
    if r.challenger_video is null and not exists (select 1 from notifications where competitor_id = r.challenger_id and type = 'upload_reminder' and data->>'duel_id' = r.id::text) then
      perform nmao.notify(r.challenger_id, 'upload_reminder', 'Upload reminder ⏰', 'Your duel upload window closes soon — submit your video!', jsonb_build_object('duel_id', r.id)); n := n + 1;
    end if;
    if r.opponent_video is null and not exists (select 1 from notifications where competitor_id = r.opponent_id and type = 'upload_reminder' and data->>'duel_id' = r.id::text) then
      perform nmao.notify(r.opponent_id, 'upload_reminder', 'Upload reminder ⏰', 'Your duel upload window closes soon — submit your video!', jsonb_build_object('duel_id', r.id)); n := n + 1;
    end if;
  end loop;

  for r in select * from duels where status = 'voting' and coalesce(overtime_until, closes_vote_at) between now() and now() + interval '6 hours' loop
    if not exists (select 1 from notifications where competitor_id = r.challenger_id and type = 'voting_closing' and data->>'duel_id' = r.id::text) then
      perform nmao.notify(r.challenger_id, 'voting_closing', 'Voting closes soon', 'Your duel''s voting window is closing — rally your community!', jsonb_build_object('duel_id', r.id)); n := n + 1;
    end if;
    if not exists (select 1 from notifications where competitor_id = r.opponent_id and type = 'voting_closing' and data->>'duel_id' = r.id::text) then
      perform nmao.notify(r.opponent_id, 'voting_closing', 'Voting closes soon', 'Your duel''s voting window is closing — rally your community!', jsonb_build_object('duel_id', r.id)); n := n + 1;
    end if;
  end loop;
  return n;
end;
$$;
revoke all on function nmao.duel_reminders() from public;
grant execute on function nmao.duel_reminders() to service_role;
select cron.schedule('duel-reminders', '*/30 * * * *', $$ select nmao.duel_reminders(); $$);
